### ISSUE TITLE
Need help...

### ISSUE THREAD

**Issue by jenn-sweet** [jenn-sweet/svg-icon-sets#1]
Ok, I have no idea why my icons are not showing up.

There is something wrong and I have been looking at it way too long.

<img width="532" alt="Screen Shot 2021-10-21 at 8 23 44 PM" src="https://user-images.githubusercontent.com/77341921/138374273-0f961584-3ed5-42b0-ba8f-574ff3c22b97.png">

4% man, I just need 4% here 

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
You're using the name of the symbol as the filenames

In your links to the sprite sheet be careful with the name of the file you're pointing to.
You saved the sprite sheet as `sprite-sheet.svg` in your `images` folder so the `xlink:href` should look like
```
<svg><use xlink:href="images/sprite-sheet.svg#the-id-of-the-correct-symbol"></use></svg>
```
